name: Deploy to EC2

on:
  push:
    branches: [ main ] # Change to main if that's your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 16.171.55.221
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/chatApp-backend
            git pull origin main
            npm install
            # If using PM2 to keep it running
            pm2 restart chat-backend || pm2 start "tsx server.ts" --name chat-backend
